/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aoc;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.List;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class AppTest {
    private static final List<char[]> INPUT = List.of(
            new char[]{'0','0','1','0','0'},
            new char[]{'1','1','1','1','0'},

            new char[]{'1','0','1','1','0'},
            new char[]{'1','0','1','1','1'},

            new char[]{'1','0','1','0','1'},
            new char[]{'0','1','1','1','1'},

            new char[]{'0','0','1','1','1'},
            new char[]{'1','1','1','0','0'},

            new char[]{'1','0','0','0','0'},
            new char[]{'1','1','0','0','1'},

            new char[]{'0','0','0','1','0'},
            new char[]{'0','1','0','1','0'}
            );
    App classUnderTest;

    @BeforeEach
    void createSubject() {
        classUnderTest = new App(INPUT);
    }

    @Test void part1SumsInput() {
        assertEquals(198, classUnderTest.getSolutionPart1());
    }

    @Test void part2MultipliesInput() {
        assertEquals(2, classUnderTest.getSolutionPart2());
    }
}