/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aoc04;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.ArrayList;
import java.util.List;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class AppTest {
    private static final List<Integer> numbers =
            List.of(7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1);

    private static Board board1 = new Board(List.of(
            "22 13 17 11  0",
            " 8  2 23  4 24",
            "21  9 14 16  7",
            " 6 10  3 18  5",
            " 1 12 20 15 19"));

    private static Board board2 = new Board(List.of(
            " 3 15  0  2 22",
            " 9 18 13 17  5",
            "19  8  7 25 23",
            "20 11 10 24  4",
            "14 21 16 12  6"));

    private static Board board3 = new Board(List.of(
            "14 21 17 24  4",
            "10 16 15  9 19",
            "18  8 23 26 20",
            "22 11 13  6  5",
            " 2  0 12  3  7"
    ));

    private static final List<Board> boards = new ArrayList<>();

    static  {
        AppTest.boards.add(board1);
        AppTest.boards.add(board2);
        AppTest.boards.add(board3);
    }

    App classUnderTest;

    @BeforeEach
    void createSubject() {
        classUnderTest = new App(numbers, boards);
    }

    @Test void part1SumsInput() throws Exception {
        assertEquals(4512, classUnderTest.getSolutionPart1());
    }

    @Test void part2MultipliesInput() {
        assertEquals(0, classUnderTest.getSolutionPart2());
    }
}