/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aoc;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class AppTest {
    private static final List<Integer> numbers =
            List.of(7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1);

    /**
     * Points group 1
     */
    private static aoc.Point[] pointsRow10 = {
            new aoc.Point(22, false),
            new aoc.Point(13, false),
            new aoc.Point(17, false),
            new aoc.Point(11, false),
            new aoc.Point(0, false),};
    private static aoc.Point[] pointsRow11 = {
            new aoc.Point(8, false),
            new aoc.Point(2, false),
            new aoc.Point(23, false),
            new aoc.Point(4, false),
            new aoc.Point(24, false),};
    private static aoc.Point[] pointsRow12 = {
            new aoc.Point(21, false),
            new aoc.Point(9, false),
            new aoc.Point(14, false),
            new aoc.Point(16, false),
            new aoc.Point(7, false),};
    private static aoc.Point[] pointsRow13 = {
            new aoc.Point(6, false),
            new aoc.Point(10, false),
            new aoc.Point(3, false),
            new aoc.Point(18, false),
            new aoc.Point(5, false),};
    private static aoc.Point[] pointsRow14 = {
            new aoc.Point(1, false),
            new aoc.Point(12, false),
            new aoc.Point(20, false),
            new aoc.Point(15, false),
            new aoc.Point(19, false),};
    private static aoc.Point[][] points1 =
            new aoc.Point[][]{pointsRow10, pointsRow11, pointsRow12, pointsRow13, pointsRow14};
    private static aoc.Board board1 = new aoc.Board(points1);

    /**
     * Points group 2
     */
    private static aoc.Point[] pointsRow20 = {
            new aoc.Point(3, false),
            new aoc.Point(15, false),
            new aoc.Point(0, false),
            new aoc.Point(2, false),
            new aoc.Point(22, false),};
    private static aoc.Point[] pointsRow21 = {
            new aoc.Point(9, false),
            new aoc.Point(18, false),
            new aoc.Point(13, false),
            new aoc.Point(17, false),
            new aoc.Point(5, false),};
    private static aoc.Point[] pointsRow22 = {
            new aoc.Point(19, false),
            new aoc.Point(8, false),
            new aoc.Point(7, false),
            new aoc.Point(25, false),
            new aoc.Point(23, false),};
    private static aoc.Point[] pointsRow23 = {
            new aoc.Point(20, false),
            new aoc.Point(11, false),
            new aoc.Point(10, false),
            new aoc.Point(24, false),
            new aoc.Point(4, false),};
    private static aoc.Point[] pointsRow24 = {
            new aoc.Point(14, false),
            new aoc.Point(21, false),
            new aoc.Point(16, false),
            new aoc.Point(12, false),
            new aoc.Point(6, false),};
    private static aoc.Point[][] points2 =
            new aoc.Point[][]{pointsRow20, pointsRow21, pointsRow22, pointsRow23, pointsRow24};
    private static aoc.Board board2 = new aoc.Board(points2);

    /**
     * Points group 3
     */
    private static aoc.Point[] pointsRow30 = {
            new aoc.Point(14, false),
            new aoc.Point(21, false),
            new aoc.Point(17, false),
            new aoc.Point(24, false),
            new aoc.Point(4, false),};
    private static aoc.Point[] pointsRow31 = {
            new aoc.Point(10, false),
            new aoc.Point(16, false),
            new aoc.Point(15, false),
            new aoc.Point(9, false),
            new aoc.Point(19, false),};
    private static aoc.Point[] pointsRow32 = {
            new aoc.Point(18, false),
            new aoc.Point(8, false),
            new aoc.Point(23, false),
            new aoc.Point(26, false),
            new aoc.Point(20, false),};
    private static aoc.Point[] pointsRow33 = {
            new aoc.Point(22, false),
            new aoc.Point(11, false),
            new aoc.Point(13, false),
            new aoc.Point(6, false),
            new aoc.Point(5, false),};
    private static aoc.Point[] pointsRow34 = {
            new aoc.Point(2, false),
            new aoc.Point(0, false),
            new aoc.Point(12, false),
            new aoc.Point(3, false),
            new aoc.Point(7, false),};
    private static aoc.Point[][] points3 =
            new aoc.Point[][]{pointsRow30, pointsRow31, pointsRow32, pointsRow33, pointsRow34};
    private static aoc.Board board3 = new aoc.Board(points3);

    private static final List<aoc.Board> boards = new ArrayList<>();

    static  {
        AppTest.boards.add(board1);
        AppTest.boards.add(board2);
        AppTest.boards.add(board3);
    }

    App classUnderTest;

    @BeforeEach
    void createSubject() {
        classUnderTest = new App(numbers, boards);
    }

    @Test void part1SumsInput() {
        assertEquals(4512, classUnderTest.getSolutionPart1());
    }

    @Test void part2MultipliesInput() {
        assertEquals(0, classUnderTest.getSolutionPart2());
    }
}