/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aoc;

import static org.junit.jupiter.api.Assertions.assertEquals;
import java.util.List;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class AppTest {
    private static final List<Command> INPUT = List.of(
            new Command("forward", 5),
            new Command("down", 5),
            new Command("forward", 8),
            new Command("up", 3),
            new Command("down", 8),
            new Command("forward", 2));

    App classUnderTest;

    @BeforeEach
    void createSubject() {
        classUnderTest = new App(INPUT);
    }

    @Test void part1SumsInput() {
        assertEquals(150, classUnderTest.getSolutionPart1());
    }

    @Test void part2MultipliesInput() {
        assertEquals(900, classUnderTest.getSolutionPart2());
    }
}